# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O6AbLfgr4NWDf2a_ZshyHVCcfj_yur1S
"""

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("rasm.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("rasm2.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("rasm3.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("rasm4.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("rasm5.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)